### ISSUE TITLE
Reactive DataStore / Node Attribute change Listener

### ISSUE THREAD

**Issue by tunjid** [zsmartsystems/com.zsmartsystems.zigbee#1267]
**Is your feature request related to a problem? Please describe.**
I'm having some trouble managing and syncing application state between my server and multiple clients, especially when one client modifies the attribute of a node; say turns a ZigBee bulb on or off.

**Describe the solution you'd like**
Is there a way we could have a callback or reactive attribute update listener? A way to broadcast that some attribute on some node has changed?

**Describe alternatives you've considered**
I tried using the `ZigbeeConsoleReportingSubscribeCommand`, but I'm not sure how it's updates are broadcast.

Alternatively, if all attribute writes cause the DataStore to be updated, I can hook into the `writeNode` implementation of my `ZigbeeNetworkDataStore`

**Additional context**
Context is I have multiple Android devices connecting to a single Android device as my ZigBee home automation server. If Client device 1 turns switch 1 on, I need to broadcast that change to client device 2. The main issue is detecting the change.

**Comment by cdjackson** [comment]
You should have a look at binding, then reporting. If you’re not familiar with how ZigBee works then I would suggest reading up on these two concepts first. The framework provides the functionality to perform these tasks so that devices send reports when something changes. 

The framework also allows you to set up a listener so that whenever an attribute updates report is received, or a command is received to a cluster, your application is notified.
