### ISSUE TITLE
Dedicated loggers for ASH and EZSP traffic

### ISSUE THREAD

**Issue by mikomarrache** [zsmartsystems/com.zsmartsystems.zigbee#1351]
Hi Chris,

I would like to submit a PR that will create dedicated loggers for ASH and EZSP traffic.

Every logger will only be used to log TX/RX frames.

The ASH logger will be used when ASH debugging is needed while the EZSP logger will be used for debugging at a higher level (after parsing).

Are you okay with that proposal?

Thanks

**Comment by cdjackson** [comment]
Hi Michael,

I’m not sure I completely understand - do you mean adding another logger in these classes that is exclusively used to log the RX/TX traffic rather than the logger that exists now?  I guess that’s probably ok, although I would question what the advantage is from the current system as I think the log configuration filtering should already allow you to separate this into separate files if that’s the intention (although I’ve not checked the filtering docs so maybe I’m wrong?).

Chris

**Comment by cdjackson** [comment]
Closed by #1350
