### ISSUE TITLE
Confused about the EzspDecisionId implementation

### ISSUE THREAD

**Issue by toth-istvan-zoltan** [zsmartsystems/com.zsmartsystems.zigbee#1443]
Hi!

First of all, thanks for the library, it is very useful.

And the actual question: I'm a bit confused about the constant values in EzspDecisionId and how they map to the EZSP reference guide.

For example: `EzspDecisionId.EZSP_ALLOW_JOINS` has a value of 0x0000 but in `UG100 - EZSP Reference Guide [4.4].pdf` the `EZSP_DECISION_ALLOW_JOINS` bit mask is 0x0001. How are these two related? I understand that one is a bit mask and the other is a value but I don't see the connection between the masks in the code and the values in the documentation.

Thanks in advance,
Istvan Zoltan Toth

**Comment by cdjackson** [comment]
This enumeration has evolved over time - unfortunately (IMHO) Silabs are not so good at evolving their firmware in a backward compatible way. Previously (I think in V3) they used a bitmask, but this changed to an enumeration at some point (I think 4.0).

In V4.4 that you reference `EzspDecisionId.EZSP_ALLOW_JOINS ` doesn't exist (you are looking at the bitmask rather than the policy id). The calls to set the policy use the `EzspDecisionId` and not the `EzspDecisionBitmask`.

Probably this does need a tidy up though and I'll take another look when I get a chance.
