### ISSUE TITLE
Mesh update exception and Readsync exception at shutdown

### ISSUE THREAD

**Issue by openhab-5iver** [zsmartsystems/com.zsmartsystems.zigbee#169]
2.3.0.201801052345 

When stopping the zigbee binding, the "Mesh update exception' occurs every time, but always only five times. Five of my devices are currently powered off (one battery and 4 GE Link bulbs). The 'Readsync exception' occurs right before these, but not every time. After starting again, everything looks good.

[010618 readsync exception.zip](https://github.com/zsmartsystems/com.zsmartsystems.zigbee/files/1608722/010618.readsync.exception.zip)

Correction... six devices are powered off (one battery and five bulbs).

**Comment by cdjackson** [comment]
I commented on this in our private discussion - this is the [interrupted exception](https://docs.oracle.com/javase/7/docs/api/java/lang/InterruptedException.html).  The reason is that the binding is stopping, and the threads are closing, so the thread is interrupted. I could silently ignore these exceptions I guess - it just means changing the way exceptions are caught.

**Comment by openhab-5iver** [comment]
OK. It was the Readsync that looked different. It's on shutdown, so don't affect anything... just jump out at you when watching for exceptions. :)

**Comment by cdjackson** [comment]
Yep - understood. Leave this open and I think I’ll change to silently ignore these exceptions - I do this in some places, but it depends on the location and what other exceptions are also being trapped.
