### ISSUE TITLE
Question: Ember: What was the failure mode that let to network state polling in ZigBeeDongleEzsp  ?

### ISSUE THREAD

**Issue by sesuncedu** [zsmartsystems/com.zsmartsystems.zigbee#805]
Is my understanding of this correct?

- The effect of polling seems to be to cause the ASH / SPI handlers to go offline if frames can't be exchanged successfully
- It only has an effect when the NCP is not in active use.
- It only checks the ASH/SPI frame layers.
- If ASH frames are received and ACKed, but higher layers are non-responsive, it will not detect an error, since nothing is waiting for or checking the response. 
- ZigBeeSerialPort does not relay  errors  from jssc
- jssc does not relay most system call errors

Is there a case where the

**Comment by cdjackson** [comment]
The purpose is to set the network to OFFLINE so that higher layers can take action and restart the system. This provides a system notification through the ```ZigBeeNetworkManager``` to allow the application to restart. This allows us to recover from a situation where the NCP needs to be restarted since the only way to do this is at application level.

**Comment by sesuncedu** [comment]
My question is really about level:

1. Should ZigBeeDongleEzsp be checking status at the  EZSP level  (i.e. waiting for timely result to  e.g. nop or echo)?
2. Should the port drivers be responsible for detecting errors at the device level?

Also, since fail modes that cause failures for outgoing commands can be detected when an outgoing command fails,  the failure modes that are of interest here is where there is no normal outgoing traffic, async callbacks are in use, the dongle fails,  the serial port does not signal an error, and incoming callbacks are not received.  
 It would seem that the decision on whether to poll should be based on the time since the last received frame, rather than the last transmitted?

**Comment by cdjackson** [comment]
> Should ZigBeeDongleEzsp be checking status at the EZSP level (i.e. waiting for timely result to e.g. nop or echo)?

This is basically what we have isn't it? There is periodic polling in ```ZigBeeDongleEzsp```. I used the network state since it provides some useful information and is also an immediate responder.

> Should the port drivers be responsible for detecting errors at the device level?

What do you mean by "port driver"? Do you mean the dongle or the serial driver? If you mean the serial driver, then it will likely not allow detection of problems such as the NCP firmware hanging up, and even if it could detect this, it cannot recover.

> the failure modes that are of interest here

We want to detect if the NCP firmware hangs - this can only be detected by sending a command. Yes, we could wait till the next command, but that might be in several hours so we added polling. I don't think there's a lot of scope for changing this too much.

> It would seem that the decision on whether to poll should be based on the time since the last received frame, rather than the last transmitted?

Yes, we could do this if it's worth it. This is how the SPI polling works, but I'm not sure there's a lot of gain to be had.

**Comment by sesuncedu** [comment]
> This is basically what we have isn't it? There is periodic polling in ZigBeeDongleEzsp. I used the network state since it provides some useful information and is also an immediate responder.

The ezsp response (or non-response) is not checked (it falls out the end of the message handling code).

**Comment by cdjackson** [comment]
It doesn’t matter - if there is no response then this is picked up elsewhere as ASH requests will fail, the system will timeout and the dongle will be set offline. The polling is only needed to keep communications to the NCP running.

**Comment by cdjackson** [comment]
If this question has been answered, can it be closed?
